DROP TABLE IF EXISTS users, items, bookings, comments, requests;

CREATE table IF NOT EXISTS users(
    id bigint generated by default as identity primary key,
    email varchar NOT NULL,
    name varchar NOT NULL
);
CREATE unique index if not exists user_email_uindex ON users (email);

CREATE table IF NOT EXISTS items(
    id bigint generated by default as identity primary key,
    name varchar(50) NOT NULL,
    description varchar NOT NULL,
    is_available boolean,
    owner_id bigint REFERENCES users (id) ON DELETE CASCADE
);

CREATE table IF NOT EXISTS bookings(
    id bigint generated by default as identity primary key,
    start_date timestamp without time zone,
    end_date timestamp without time zone,
    item_id bigint REFERENCES items (id) ON DELETE CASCADE,
    booker_id bigint REFERENCES users (id) ON DELETE CASCADE,
    status varchar NOT NULL
);

CREATE table IF NOT EXISTS comments(
    comment_id bigint generated by default as identity primary key,
    text varchar NOT NULL,
    created timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    item_id bigint REFERENCES items (id) ON DELETE CASCADE,
    author_id bigint REFERENCES users (id) ON DELETE CASCADE
);

CREATE table IF NOT EXISTS requests(
    request_id bigint generated by default as identity primary key,
    description varchar NOT NULL,
    requestor_id bigint REFERENCES users (id) ON DELETE CASCADE,
    created timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE items ADD COLUMN target_request_id bigint REFERENCES requests (request_id) ON DELETE CASCADE;